---
title: "Задача №3"
runtime: shiny
output: html_document
---

## Умова задачі

В Мікроландії в умовах досконалої конкуренції діють 100 фірм з виробничою функцією $y={\alpha_0} K^{\alpha_1}L^{\alpha_2}$, де $y$ – обсяг продукції у тис. штук, $K$ – капітал фірми, $L$ – кількість найманих працівників. Ціна готової продукції становить 15 гр.од. Коефіцієнти виробничої функції у кожної
фірми різні. Кількість устаткування на фірмах може приймати такі значення: 1 (40% фірм), 2 (20%), 2,5 (20%), 3 (20%). Визначити, якою буде рівноважна ставка заробітної плати, якщо функція пропозиції праці становить $S_L=30w-120$

## Розвя'зок

Користувач приймає такі вхідні значення:

1) Межі коефіцієнтів виробничої функції
2) Тип похибки 

Програма генерує рівномірний розподіл коефіцієнтів виробничої функції в межах, що задані користувачем. Також, кількість устаткування випадковим чином розподіляється між фірмами.

Спочатку зробимо деякі перетворення.
Перетворивши ринкову функцію пропозиції праці, отримаємо:
$w=(L_m + 120)/30$, де $L_m = L_1+L_2+..L_{100}$, де $L_1$ - кількість робітників, що найме перша фірма, де $L_2$ - кількість робітників, що найме друга фірма і т.д.
Функцію граничного продукту для фірми отримуємо диференціюванням функції виробництва:
$MP_i={\alpha_{2,i}}{\alpha_{0,i}}K^{\alpha_{1,i}}L^{\alpha_{2,i}-1}, i=1...100$,

Оскільки для конкурентного ринка справджується рівність $MP*P=w$, то процес розвязання задачі зводиться до вирішення системи нелінійних рівнянь такого вигляду:

$\begin{cases} MP_1*P=w \\ MP_2*P=w \\...\\ MP_{100}*P=w \end{cases}$

де $P$ - ринкова ціна, а $w$ - рівноважний ринковий рівень заработної плати.

В цій системі ліва частина всіх рівнянь задається похідною від функції виробництва кожної фірми а права частина випливає з ринкової функції пропозиції праці. Невідомими змінними в цій системі є кількість робітків, що найме кожна з 100 фірм. Оскільки це значення може приймати тільки цілочисельне значення, а функція граничного продукта буде нелінійною, то отримаємо задачу нелінійної цілочисельної оптимізації (Mixed-integer nonlinear optimization).

Для оптимізації будемо використовувати два типи похибки для визначення відхилень у рівностях: 

1) абсолютна похибка (сума модулів відхилень)
2) квадратична похибка (сума квадратів відхилень)

Для реалізації описаної системи будемо використовувати пакет "DEoptimR".

## Результат

В результаті отримаємо ринковий рівень заробітної плати та оптимальну кількість робітників, яку буде наймати кожна фірма.
Також, наприкинці можна завантажити файл формату *csv* з данним по кожній фірмі, в якій міститься:

* Початкові коефіцієнти виробничої функції
* Задані обсяги капіталу
* Оптимальні обсяги використання праці


