---
title: "Задача №4"
runtime: shiny
output: html_document
---

## Умова задачі та додаткові умови

Характеристики ділянки річки для цієї задачі такі: глибина – 2 метри, ширина – 10 м., швидкість течії – 1,5 м/с. Моделювання відбувається протягом одного року на поденній основі (360 періодів). Паводком вважаються періоди з середини лютого до кінця березня, під час якого витрати води в річці підвищуються на 10%.

Промислове підприємство розташоване у верхній частині ріки. Тваринницький комплекс (ферма) розташований в середині течії річки на відстані 4 км від промислового підприємства. Пересувна станція контролю якості води може розташовуватись на відстані від 0 до 3 км від ферми з кроком 500 метрів. 

Загалом, граничні значення для початкової кількості свиней та корів задаються відповідно до умови. Кожного періоду продається одна свиня та одна корова. В той же час, відбувається вирощування нових тварин, серед яких 30 нових свиней з’являються кожні 70 днів, а 10 нових корів кожні 150 днів. Ціна однієї свині становить 500 ум.од., а корови – 1000 ум.од, однієї виробленої одиниці продукції – 1000 ум.од.

На сільгоспугіддях можна вирощувати пшеницю, жито, ячмінь, кукурудзу та картоплю. Ціни становлять 2 ум.од, 2 ум.од, 5 ум.од, 5,5 ум.од, 7 ум.од. Максимальна площа, яку можна засіяти кожною культурою, становить 50 га. Підвищення урожайності враховується пропорційно загальній внесеній кількості добрив: якщо всі добрива внесена максимально, то врожайність всіх культур також збільшується максимально. Середні, максимальні врожайності кожної культури та вартість добрив встановлені на основі інформації з Інтернету.

Розрахунок необхідного ступеня очистки води відповідно до законодавчих норм відбувається на основі формул за посиланням: [link 1](https://www.chem-astu.ru/chair/study/engmet-ooc/?p=193), [link 2](http://lib.ssga.ru/fulltext/umk/auumk/ecology/rab5_2.htm), [link 3](https://studopedia.info/4-109769.html). Норми БПК обрані для використання водойми для питних потреб. У програмі можна використовувати 3 види очищення для промислового підприємства та ферми: нічого не очищувати, очищувати 50% викидів, очищувати повністю відповідно до норм. Використання кожного ряду лісонасаджень зменшує забруднення з полів на 20%, оранка та штучна аєрація – на 30%. Загалом, витрати на очищення 1% забруднень кожного виду складає 500 ум. од., а економічні збитки від погіршення якості води на 1% становить 500 ум. од. Власні витрати населення, пов'язані з поїздками на відпочинок в інші місця становить 5000 ум. од. кожного дня в літній період.

Гравці мають можливість: вибрати інтенсивність роботи підприємства, вид і кількість тварин на фермі (на початку гри), вибрати сільськогосподарські культури для вирощування й необхідну для досягнення врожаю кількість добрив та отрутохімікатів, вибрати методи очищення стоків з підприємства і ферми, визначити місце розташування ПСК на річці, застосувати інші природоохоронні заходи.

## Результат

В результаті роботи буде отримано прибуток, як різницю між доходами (підприємства, ферми, полів) та витратами (очистка води, витрати на добрива та вирощування сільськогосподарських культур). Також, в результаті буде отримано значення економічного збитку як втрат від захворювань населення, витрат закладів охорони здоров'я у зв'язку з хворобами населення, що виникають через забруднення навколишнього середовища, власних витрат населення, пов'язаних з поїздками на відпочинок в інші місця. Ці дані виведені в текстовому вигляді та графічно кумулятивним підсумком.



