library(shiny)
library(markdown)



shinyUI(navbarPage("Задача №4", 
                   tabPanel("Результат", 
                            fluidPage(
                                tags$style(type="text/css",
                                           ".shiny-output-error { visibility: hidden;}",
                                           ".shiny-output-error:before { visibility: hidden;}"),
                                textOutput("text1"),
                                plotOutput("plot1"),
                                
                                hr(),
                                
                                fluidRow(
                                    column(3,
                                           h3("Діяльність заводу та ферми:"),
                                           sliderInput("y_factory",
                                                       "Інтенсивність роботи підприємства, шт.",
                                                       min = 0,
                                                       max = 150,
                                                       value = 100),
                                           sliderInput("n_svin",
                                                       "Кількість свиней:",
                                                       min = 0,
                                                       max = 2000,
                                                       value = 500),
                                           sliderInput("n_korov",
                                                       "Кількість коров:",
                                                       min = 0,
                                                       max = 1000,
                                                       value = 500),
                                           h3("Методи очистки:"),
                                           selectInput("point_clean_factor",
                                                       "Очитка стоків із заводу:",
                                                       choices = list("Nothing" = 0, "50%" = 1,
                                                                      "100%" = 2), 
                                                       selected = 1),
                                           selectInput("point_clean_factor_2",
                                                       "Очитка стоків із ферми:",
                                                       choices = list("Nothing" = 0, "50%" = 1,
                                                                      "100%" = 2), 
                                                       selected = 1),
                                           selectInput("adj_pollution_polya_lis",
                                                       "Лісонасадження",
                                                       choices = list("Nothing" = 0, "1" = 1,
                                                                      "2" = 2, "3" = 3), 
                                                       selected = 1),
                                           checkboxInput("adj_pollution_polya_aero", "Оранка", value = TRUE),  
                                           checkboxInput("adj_pollution_polya_oranka", "Штучна аерація", value = TRUE),  
                                           selectInput("L_position",
                                                       "Позиція ПСК від ферми (вниз по річці):",
                                                       choices = list("0" = 0, "1" = 1,"2" = 2, "3" = 3,"4" = 4, "5" = 5, "6" = 6),
                                                       selected = 2), 
                                           checkboxInput("showPlot_n", "Показати/Сховати графік 1", value = TRUE),
                                           submitButton("Submit")
                                    ),
                                    column(4, offset = 1,
                                           h3("Сільськокосподарські кільтури:"),
                                           sliderInput("zito_plosha",
                                                       "Початкова площа засадження жита, га",
                                                       min = 0,
                                                       max = 50,
                                                       value = 25),
                                           sliderInput("kykyr_plosha",
                                                       "Початкова площа засадження кукурдзи, га",
                                                       min = 0,
                                                       max = 50,
                                                       value = 25),
                                           sliderInput("yachmin_plosha",
                                                       "Початкова площа засадження ячменю, га",
                                                       min = 0,
                                                       max = 50,
                                                       value = 25),                                    
                                           sliderInput("pshen_plosha",
                                                       "Початкова площа засадження пшениці, га",
                                                       min = 0,
                                                       max = 50,
                                                       value = 25),
                                           sliderInput("kart_plosha",
                                                       "Початкова площа засадження картоплі, га",
                                                       min = 0,
                                                       max = 50,
                                                       value = 25)  
                                           
                                    ),
                                    column(4,
                                           h3("Використання добрив:"),
                                           sliderInput("dobr_az",
                                                       "Кількість внесених азотних добрив, кг/га",
                                                       min = 0,
                                                       max = 50,
                                                       value = 10),                                    
                                           sliderInput("dobr_ka",
                                                       "Кількість внесених калійних добрив, кг/га",
                                                       min = 0,
                                                       max = 50,
                                                       value = 10),  
                                           sliderInput("dobr_fo",
                                                       "Кількість внесених фосфатних добрив, кг/га",
                                                       min = 0,
                                                       max = 50,
                                                       value = 10),  
                                           sliderInput("dobr_org",
                                                       "Кількість внесених органічних добрив, кг/га%",
                                                       min = 0,
                                                       max = 20000,
                                                       value = 10000),  
                                           sliderInput("dobr_vapno",
                                                       "Кількість внесеного вапна, кг/га",
                                                       min = 0,
                                                       max = 2000,
                                                       value = 1000),  
                                           sliderInput("dobr_metafos",
                                                       "Кількість внесеного метафосу, кг/га",
                                                       min = 0,
                                                       max = 30,
                                                       value = 10),  
                                           sliderInput("dobr_hvorob",
                                                       "Кількість внесеного засобу боротьби з хворобами, кг/га",
                                                       min = 0,
                                                       max = 3.5,
                                                       value = 1.5),  
                                           sliderInput("dobr_byrian",
                                                       "Кількість внесеного засобу боротьби з бурянами, кг/га",
                                                       min = 0,
                                                       max = 6,
                                                       value = 2)                                    
                                           
                                           
                                    )
                                )
                            )

                   ), 
                   tabPanel("Опис моделі",
                            mainPanel( 
                                includeMarkdown("about.Rmd") 
                            ) 
                   ) 
) 
)    
