---
title: "about"
author: "Bilychenko"
date: "February 4, 2019"
output: 
    html_document:
        mathjax: "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
runtime: shiny
---

## Опис задачі

Модель побудована на таких додакових припущеннях:

1. Народжуваність - 3%, смертність - 1%, кожний показник має розподіл Пуасона.

2. Початково ніхто не робить внески.

3. Показники швидкості розповсюдження та смертельності зростають кожного періоду на 1%.

4. Функція, що визначає частку внесків, пропорційна кількості померлих за певний період часу у минулому.  
Загалом, в цій моделі початкові 10 періодів індивіди не витрачають на боротьбу з цим вірусом грошей та спостерігають. Після цього, частка їх витрат встановлюється пропрційною приросту кількості загиблих за 10 періодів до цього.

5. Критичний момент - період, коли кількість загиблих починає знижуватись. 

6. Початково задаються коефіцієнти швидкості розповсюдження, смертності, росту частки після досягнення критичного моменту, розміри населення, базовий фонд на дослідження.

7. Також задається розмір обчислювальних можливостей.

В результаті буде побудовано 2 графіки: смертності від хвороби та загальної кількості населення.
Також, буде 3 варінти кінцевого результату:

1. Знайдено оптимальний рівень витрат та період, коли буде повністю подолано хворобу.

2. Всі жителі помруть.

3. Недостатньо потужностей.

## Інструкція щодо початкових значень

Спочатку треба визначити деякі початкові параметри:

1. Швидкість розповсюдження вірусу (від 1% до 100%)

2. Смертність вірусу (від 1% до 100%)

3. Фіксований приріст частки витрат, після досягнення піку смертності (від 0,01% до 10%)

4. Далі, задається 3 параметри, які регулюють:

* обчислювальні можливості (малі, середні, великі)

* початковий розмір фонду на боротьбу з вірусом (малий, середній, великий)

* початкова кількість населення (мала - 10^4, середня - 10^10, велика - 10^15)

5. Далі обирається можливість корекції функції витрат після проходження піку смертності.

6. Далі можливість відображення графіків кількості загиблих внаслідок вірусу людей та загальної кількості населення.

## Відповіді на питання із задачі.

Загалом, за цією моделлю та відповідною функцію витрат може бути досить поступове та довге зниження кількості хворих, якщо населення не змінить свою функцію витрат на дослідження після проходження піку смертності.
В більш широкому випадку (за іншої функції витрат), я вважаю, що кількість загиблих буде вести себе циклічно, поступово знижуючись, а потім знову підвищуватись і т.д.

