---
title: "Задача №7"
runtime: shiny
output: html_document
---

## Умова задачі

У Мікроландії проживає три рівні за розміром групи індивідів, кожна з яких має такі функції корисності: $u_1=x$, $u_2=x^2$, $u_3={\sqrt(x)}$, де $x$ - кількість грошей. Держава намагається підтримувати рівень злочинності на рівні не вище 5%, змінюючи тяжкість покарання $F$ та імовірність викриття злочину $p$, яка прямо пропорційно залежить від рівня фінансування поліції, рівня податків $b$. Оплата в легальному секторі здійснюється в залежності від кваліфікації робітника на 3 рівнях: 1400 гр.од., 2100 гр.од., 4500 гр.од. Працівники першого рівня можуть вкрасти 5200 гр.од., другого - 10000 гр.од., третього - 35000 гр.од. Написати ІС, яка за вказаними параметрами змоделює діяльність економіки протягом перших 1000 днів. Написати алгоритм вибору оптимальних значень $F$ та рівня фінансування поліції. Фінансування поліції здійснюється за рахунок штрафів $F$ та податків за попередній період (з усіх легальних зарплат ставка податку $b$).

## Розвя'зок

Спочатку розраховується очікувана злочинцем корисність від скоєння злочину. Далі, на основі отриманого значення для кожної особи отримуємо попередню змінну вибору: якщо більше 0, то злочинцю буде вигідно здійснити злочин. Але, вводиться додаткове припущення: якщо наявний дохід індивіда менший за розмір штрафу (тобто, він не зможе його виплатити), то індивід не буде скоювати злочин.

Далі, відбувається розрахунок доходу, що належить кожній особі: попередній рівень доходу разом з 50% офіційної заробітної плати та обсягу кражі, якщо вона була.

Далі випадковим чином відбувається накладання штрафу на певний відсоток злочинців та відповідне зменшення їх доходів. Також, відбувається розрахунок надходжень за рахунок податків та суми штрафів.

Якщо користувач обрав оптимізацію рівня штрафів, то після певного періоду накопичення фінансування відбувається корекція суми штрафу пропорційна до росту фінансування у цьому періоді в порівнянні з минулим. Аналогічно, якщо вибрана оптимізація ймовірності то відбувається пропорційне до росту фінансування зростання ймовірності знаходження злочинця.

Загалом, на початку користувач задає 3 параметри (рівень злочинності, штраф, рівень податків на фінансування боротьби) та можливість оптимізації розміру штрафу  чи/або ймовірності знаходження злочинця.

## Результат

В результаті обчислень, отримується середній рівень злочинності на всьому часовому періоді та динаміку зміни цього показника.


