---
title: "about"
author: "Maksym Bilychenko"
date: "February 16, 2019"
output: 
    html_document:
        mathjax: "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
runtime: shiny
---

## Опис задачі

У Мікроландії живуть $n$ осіб, кожна з яких має функцію корисності  $u(x_1,x_2)=x^{\alpha_1}_1x^{\alpha_2}_2{}$, де $x_1, x_2$ – кількості товарів, причому для кожного жителя виконуються співвідношення ${\alpha_1}+{\alpha_2}=1, {\alpha_1}\geq0,{\alpha_2}\geq0$, всі коефіцієнти – випадкові величини з проміжку від 0 до 1. Всі індивіди мають доходи у розмірі $b_i\in[b_{min}; b_{max}].$ Кожного періоду ціна на один з товарів зростає на $r$%. Держава у кожному періоді компенсує всім індивідам зміну цін на величину останнього розрахованого ефекту доходу. Створити програму, яка для заданих $n$, цін товарів, початкових меж доходів, зміни $r$, моделює загальний обсяг споживання товарів у країні у кожному періоді, розраховує для кожного періоду індекс цін Пааше, Ласпейреса, Фішера, сумарну величину компенсації. 

## Інструкція щодо роботи програми

Спочатку треба визначити деякі початкові параметри:

* Кількість періодів для моделювння (від 10 до 1000)

* Чисельність населення (від 10 до 1000)

* Визначити межі початкового доходу

* Визначити ріст ціни кожного періоду (від 1% до 50%)

* Задати початкові ціни на товар 1 та товар 2

* Обрати метод для розрухунку ефектів доходу

Загалом, програма складається з кількох блоків. Загальний алгоритм роботи програми можна описати наступним чином:

1. Зчитування початкових параметрів та ініціалізація всіх змінних

2. Визначення початкової рівноваги.

3. Випадковим чином визначення товару, ціна на яку буде підвищено. Оновлення цін.

4. Визначення нової рівноваги.

5. Визначення точки рівноваги для розрахунку ефектів доходу за методом Хікса чи Слуцького. *Зауваження: для розрахунку нової точки за методом Хікса відбувається вирішення нелінійного рівняння, тому процес моделювання може займати більше часу.*

6. Визначення ефекту доходу та розміру компенсації. Оновлення доходу наступного періоду на рівень компенсації для кожного мешканця.

7. Ітеративне процес повторення пунктів 3-6 для заданої кількості періодів.

8. Виведення результатів: таблиці даних для завантаження та графіків.


## Результати

В результаті роботи програми створюється 5 графіків та таблиця даних для завантаження.
Графіки показують відповіді на питання задачі:

1. Обсяги споживання кожного товару та ціну на них у часі (графіки 1-3).

2. Розраховані індексі Ласпейреса, Пааше та Фішера у часі та згладжені дані кожного індексу для розуміння загальних тенденцій.

3. Сумарну величину компенсації у кожному періоді (наростаючим підсумком).

