---
title: "Задача №3"
runtime: shiny
output: html_document
---

## Умова задачі

У Мікроландії, де проживає 2540 робітників, у домогосподарствах не прийнято накопичувати гроші. Всі робітники зайняті або на державній службі (100 осіб, зарплата – 750 динарів), або на неприбутковому заводі-монополісті устаткування, або на 3 фірмах, що випускають готову продукцію. Державні службовці займаються лише збором податків, та виплатою допомоги непрацюючим особам (150 динарів). Виробнича функція завода-монополіста $Q_M=12*L$ , де $L$ – кількість найнятих працівників, фіксовані витрати на утримання заводу становлять 2100 динарів. Свою продукцію завод продає фірмам, які мають наступні виробничі функції: $Q_1(K,L)=L{\sqrt(K)}$ , $Q_2(K,L)=K{\sqrt(L)}$, $Q_3(K,L)=2{\sqrt(L)}*{\sqrt(K)}$ (K та L – кількість устаткування та людей, залучених для виробництва готової продукції). Фірми не несуть інших витрат, крім витрат на придбання факторів виробництва. В останні роки в державі не спостерігалося корупційних схем, ухиляння від податків або нечесної конкуренції. Наразі в державі рівновага, всі підприємства сплачують податок з прибутку T=25%, а всі робітники – ${\tau}$ = 13% від зарплати (держслужбовці та непрацюючі податки не сплачують). 

1) Визначити функції попиту на устаткування, готову продукцію, працю. 

2) Визначити розподіл робітників по підприємствах. 

3) Розрахувати бюджет держави.

4) Пропонується замінити податок на прибуток податком на оборот (фіксована плата з кожної одиниці виробу, яка є різною для різних типів підприємств). Визначити ці ставки, що максимізують державний бюджет країни. Який вплив очікується на ринок праці? 

5) Змоделювати розвиток ситуації, якщо фірми спробують об’єднатися в картель.

6) Побудувати комп’ютерну модель, якщо у Мікроландії зміниться менталітет народу і всі розпочнуть робити накопичення для більшого споживання у майбутньому (дозволяється вводити довільні нові змінні та припущення).

## Розвя'зок

Користувач задає такі вхідні значення:

1) Заробітну плату на заводі та фірмах
2) Ціну кінцевих товарів
3) Додаткові умови (картель, зміна податку, ставки податків, заощадження)

На основі принципів оптимуму розподілів ресурсів, було отримано наступні функції попиту на працю для фірм, що виробляють кінцеву продукцію

$L_1 = P_k*K_1/(2*w_1)$, $L_2 = 2*P_k*K_2/w_2$, $L_3 = P_k*K_3/w_3$, $L_i$ - кількість робітників на і-тій фірмі, $K_i$ - кількість устаткування, $w_i$ - заробітна плата, $P_k$ - ціна обладнання. 

Ми припускаємо, що завод-монополіст має 0 прибуток, а значить має місце відповідна рівність на позначення ціни капіталу, що випускає цей завод $P_k = (w_M*L_M+2100)/(12*L_M)$, де $L_M$ - кількість робітників на заводі, $w_M$ - заробітна плата працівників на заводі, $P_k$ - ціна обладнання. 

Також, у ході розв’язання припускається, що ця ціна одна для всіх компаній і весь капітал розподіляється рівномірно між 3 фірмами.

Після цього, ітеративним алгоритмом визначається множина можливих розподілів робітників, та обирається той варіант, що максимізує прибуток фірм.

За умов картелі, відбувається максимізація суми сукупного прибутку 3 фірм, що виробляють кінцеву продукцію.

Далі,  відбувається розрахунок дефіциту/профіциту бюджету держави. Доходи держави складаються з суми податків від фірм (за різними методами – податок на прибуток чи податок на оборот) та суми податків на заробітну плату.

Витрати держави становлять виплати безробітним та держслужбовцям.

При наявності у населення накопичень (змінна гранична норма до споживання), відбувається зменшення надходжень до бюджету, оскільки відкладені гроші не обкладаються податком за нашим припущення.

## Результат

В результаті обчислень, отримується оптимальний розподіл робітників між заводом-монополістом, 3 фірмами, держслужбовцями та безробітними, а також розраховується профіцит/дефіцит бюджету.

