---
title: "Задача №5"
runtime: shiny
output: html_document
---

## Умова задачі та додаткові умови

У минулому році компанія «Надкушена груша» (США) створила революційно новий гаджет «Saveourminds”, життя без якого стало зразу неможливим для 6% населення планети Земля. На жаль, компанія не може задовольнити попит на нову продукцію, оскільки не має вільних потужностей. Для виробництва гаджету необхідно будувати нові заводи, кожен з яких вводиться в експлуатацію протягом 6 місяців від моменту здійснення необхідного фінансування. У поточному році кожен завод обходиться компанії у 165,4 млн. гр.од., але за рахунок інфляції кожний наступний рік буде збільшувати вартість на 6%. На одному заводі можна виробити або 17 млн. чорних гаджетів (в основному, купують чоловіки та жінки, старші 25 років), або 16 млн. рожевих гаджетів з білим хвостиком (купуються в основному дівчатами до 25 років). За рахунок агресивної маркетингової компанії можна збільшити кількість осіб, що не можуть жити без гаджету: кількість нових осіб залежить від наданого фінансування квадратично. Проте на ринок намагаються вийти нові компанії з Китаю, що заважає монополії «Надкушеної груші». Вартість будівництва заводу для них становить у поточному році лише 97,5 млн. дол, а інфляція – 4,6%. Хоча компанії з Китаю не матимуть змоги почати фінансування заводів раніше вересня поточного року, вони активно досліджують ринок. За рахунок недотримання технології, гаджети китайських компаній цінуються значно менше серед споживачів. Припускаючи, що всі компанії на планеті Земля знаходяться на початку січня поточного року, рішення приймаються щомісячно, розробити власну імітаційну модель даної економіки, визначити оптимальні стратегії для компаній, змоделювати, яку частку ринку матиме компанія-лідер впродовж найближчих 25 років.

## Додаткові умові та коментарі до моделі

Для реалізації імітаціної моделі були використані наступні додаткові припущення:

* Цінність гаджетів китайських компаній визначається пропорційно відношенню цін на їх та американські смартфони: чим нижче ціна китайських смартфонів по відношенню до ціни 

* Надкушеної груші, тим більший буде попит на їх гаджети.

* Введення в експлуатацію заводу Надкушена груша здійснюється після 6 місяців від моменту здійснення необхідного фінансування (за умовою), а китайських заводів - після 3 місяців від фінансування.

* Витрати на виробництво реалізовані як рівномірно розподілені витрати помісячно для кожного заводу.

* Вважається, що покупці здійснюють повторну покупку кожні 6 місяців.

* Загалом, на початку року існує 15 заводів компанії Надкушена груша.

* Ця компанія може використовувати кожну з 3 стратегій (чи їх мікс):

1. Збільшувати витрати на маркетинг для розширення попиту

2. Збільшувати ціну для росту прибутку (але може бути втрата в кількості покупців)

3. Будувати нові заводи

* Компанії з Китаю за замовчуванням будують перші 3 місяці після вересня по 3 заводи, після чого їх кількість зростає відвоідно до заданого кристувачем темпу.

* Стратегії будуть застосовуватиссь, коли прибуток починає спадати.

* Умови оптимальності вважається досягнення максимального прибутку.

## Результат

В результаті роботи буде отримано графік динаміки частки фірми лідера (Надкушена груша) та середній показник частки цієї фірми на всьому проміжку. Також, для більшої наочності буде побудовано пряму згладжування на основі методу LOESS.






