---
title: "Задача №7"
runtime: shiny
output: html_document
---

## Умова задачі

Використовуючи виробничо-інституціональну функцію збору податків  $T({\theta})={\gamma*\theta}e^{\lambda*t}K^{({\alpha+\beta*\theta})\theta}L^{({n+m*\theta})\theta}$, визначити оптимальні точки Лаффера 1-го та 2-го роду в Україні, використовуючи статистичні дані з 1992 до поточного року (якщо дані є) для наступних видів податків:

а) ПДВ;
б) податок на доходи фізичних осіб;
в) податок на прибутки підприємств;
г) податок на землю.

## Розвя'зок

Перетворимо задане рівняння до певного виду:

$X={\gamma}e^{\lambda*t}K^{({a+b*\theta})\theta}L^{({n+m*\theta})\theta}$

Далі, прологарифмуємо задане рівняння та отримуємо:

$ln(X)=ln({\gamma})+{\lambda*t}+{a\theta}ln(K)+b*\theta^2ln(K)+n{\theta}ln(L)+m*\theta^2ln(L)$, де $\theta=T/X$

Для оцінки коєфіцінтів рівняння була зібрана база даних на щорічній основі наступних показників:

-	ВВП у фактичних цінах, млн грн. ($X$)
-	Вартість основних фондів (залишкова), млн. грн. ($K$)
-	Зайняте населення у віці 15-70 років, тис. Осіб ($L$)
-	Сума податкових ннадходжень за видами (ПДВ, податку на доходи, податку на прибуток, податок на землю), млн. грн ($T$)

Дані про податки були отримані за наступним [посиланням](http://cost.ua/budget/revenue/), а інші данні з сайту [Державної служби статистики України](http://www.ukrstat.gov.ua/)

Після оцінки коефіцієнтів рівняння, було розраховані точки Лафера 1 та 2 за наступними формулами:

$\theta^*=-\frac{a*lnK+b*lnL}{2*(b*lnK+m*lnL)}$

$\theta^{**}=\frac{\sqrt(a*lnK+b*lnL^2-8b*lnK+m*lnL)-a*lnK-n*lnL}{4*(b*lnK+m*lnL)}$

Зауваження: * Для деяких типпів податків розрахунок точки Лафера 2 призводить до невизначених результатів, оскільки підкореневий вираз набуває відємних значень. *

## Результат

В результаті обчислень, отримується таблиці з динамікою значень точок Лафера 1 та 2 порядку для кожного з 4 видів податку.



